[[make-tooling]]
= Using Make With AMQ 7 documentation

When you make changes to the documentation, it is a good practice to do a local test build to verify the book builds successfully and renders as you expect before you submit the merge request back to upstream master.

Make is a useful tool for building your documentation and pushing it to your public Red Hat file share so that peer and quality reviewers can see your edits as the customer would.

You can also build your documentation with xref:build-configuration[ccutil]. Be aware that only ccutil catches build errors such as invalid xrefs and missing includes.

== Make commands to build documentation

[source,options="nowrap",subs="+quotes"]
----
$ cd __PROJECT_DIR__

$ make help
[default]      Equivalent to 'make preview'
preview        Generate asciidoctor output (faster)
build          Generate ccutil and asciidoctor output (slower)
test           Run all build scripts and output checks
clean          Removes build/ and other build artifacts
publish        Copy output to http://file.rdu.redhat.com/~__USERNAME__/amq-docs/

$ make preview
[...]
----

See the output in your browser at file: `__PROJECT-DIR__/build/welcome/index.html`

The entry point for the resulting output is `build/welcome/index.html` in your checkout.

To publish your results to your personal file share, use make publish. It copies the local output to a Red Hat file server. link:https://redhat.service-now.com/rh_ess/kb_view.do?sysparm_article=KB0003945[Learn more about setting up your personal file share^].

== Make commands to refresh upstream repositories

include::amq7-upstreams.adoc[]
