[[git-tips]]
= Git tips

== Deleting branches

To delete all of your branches except the branch you are on:

[source]
----
$ git checkout contrib
$ for br in `git branch` ; do git branch -D $br ; done
----

To delete one branch:

[source,options="nowrap",subs="+quotes"]
----
$ git checkout contrib
$ git branch -D _BRANCH_NAME_
----

== Resolving conflicts

To resolve a merge conflict in an existing pull request:

[source,options="nowrap",subs="+quotes"]
----
$ git checkout _BRANCH_NAME_
$ git branch -u origin _BRANCH_NAME_
$ git pull --rebase upstream contrib
$ git push -f origin HEAD
----

== Reseting your fork

If your fork is both ahead of and behind the origin you can reset your fork to match the origin and start with a clean slate.

[source]
----
$ git checkout contrib
$ git reset --hard upstream/contrib
$ git push origin contrib --force
$ git pull upstream contrib
$ git push origin contrib --force
----

== Accessing another writer’s unmerged commits

This is the process you can use if you need commits another writer has submitted in a merge request that is not yet merged.

. Make sure you are on the contrib branch
+
[source,options="nowrap",subs="+quotes"]
----
$ git checkout contrib
----
. Check out a new topic branch from upstream/contrib as you normally do.
+
[source,options="nowrap",subs="+quotes"]
----
$ git fetch upstream
$ git checkout -b __NEW_TOPIC_BRANCH__ upstream/contrib
----
. If you have not yet added that writer’s remote repository, add it now.
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote add -f _USER_ git@github.com:__USER__/amq7-documentation-contrib.git
----
. Rebase to bring in the changes that are in that user’s outstanding
 `origin/__MERGE_REQUEST_BRANCH__` branch.
+
[source,options="nowrap",subs="+quotes"]
----
$ git rebase _USER_/_MERGE_REQUEST_BRANCH_
----
+
(you will see the following response)
+
[source,options="nowrap",subs="+quotes"]
----
First, rewinding head to replay your work on top of it...
Fast-forwarded _NEW_TOPIC_BRANCH_ to _USER_/_MERGE_REQUEST_BRANCH_
----

=== Committing to another writer's branch

If you have made changes to the content in someone else's branch you'll want to be sure to commit them back to that same branch/PR.

. While in your working branch, commit your changes
+
[source,options="nowrap",subs="+quotes"]
----
$ git commit -m "__MESSAGE__"
----
. Push your changes to the existing PR
+
[source,options="nowrap",subs="+quotes"]
----
$ git push _USER_ HEAD:__MERGE_REQUEST_BRANCH__
----
