[[setting-up-git]]
= Setting up Git

AMQ 7 uses git to manage repositories.  This guide explains how to set up your system to connect to the proper git repositories.

include::amq7-repositories.adoc[leveloffset=+1]

[[install-git]]
== Install Git

If using RHEL or Fedora, open your terminal and enter the proper installation command.

[discrete]
=== RHEL
[source]
----
$ sudo yum install git
----

TIP: To get sudo access for RHEL 7, go to Applications > Red Hat Internal > Switch the ..., and then select the *I need sudo access* checkbox.

TIP: To bypass the need for sudo access go to Applications > System Tools > Software, and in the Search box, type Git and press Enter. Select the check box for "Fast Version Control System git-1.8.3.1-6.el7_2.1 (64-bit)" and press *Enter* to install.

[discrete]
=== Fedora
[source]
----
$ yum install git (up to Fedora 21)
$ dnf install git (Fedora 22 and later)
----

[discrete]
=== Other Operating Systems

* https://git-scm.com/downloads[Download Git^]

[[configure-git]]
== Configuring Git

Once you have git installed you'll want to set up your git account.

.Procedure
. Open *Terminal*
. Set your name and email
+
[source,options="nowrap",subs="+quotes"]
----
$ git config --global user.name "__YOUR_NAME__"
$ git config --global user.email "__YOUR_EMAIL__"
----
+
TIP: The email you specify should be the same one found in your https://help.github.com/articles/adding-an-email-address-to-your-github-account/[email settings^]. To keep your email address hidden, see https://help.github.com/articles/keeping-your-email-address-private[Keeping your email address private^].

. Set your git defaults
+
[source]
----
$ git config --global pull.rebase true
$ git config --global push.default simple
----

[[fork-upstream]]
== Fork the Upstream (GitHub) Repository

Fork the `amq7-documentation-contrib` upstream repository to create a copy under your own GitHub ID. This allows you to work on multiple features and push changes to branches in your own GitHub instance so that you do not have to worry about losing work. When you are ready, you can request the changes to be merged back into the upstream repository.

.Procedure
. Open a browser and navigate to the upstream repository located at link:https://github.com/rh-messaging/amq7-documentation-contrib[https://github.com/rh-messaging/amq7-documentation-contrib^]
. Click *Fork* located in the upper right under your profile icon.
. Select your user account for the location of the forked repository. This creates your own copy of the repository under your own GitHub ID.

[[add-ssh-github]]
== Add Your SSH Keys to GitHub

If you choose to use the SSH address for your clones, you will need to add an SSH Key to GitHub first.

.Procedure
. Open *Terminal*.
. Check to see if you have a public SSH key:
+
[source]
----
$ ls ~/.ssh/
----
. If you don't have a key, generate one:
+
[source,options="nowrap",subs="+quotes"]
----
$ ssh-keygen -t rsa -C "__YOUR_EMAIL__"
----
. Open your key in an editor:
+
[source]
----
$ cd ~/.ssh/
$ vi id_rsa.pub
----
. Copy the contents of the file to your clipboard.
. Visit link:https://github.com/settings/keys[https://github.com/settings/keys^]
. Click *New SSH Key*.
. Give your key a name and paste the contents of your key file.
. Click *Add SSH Key*.

[[clone-forked]]
== Clone Your Forked Upstream Repository

Clone your forked repository to bring your GitHub repository files to your local machine. Your forked repository is now the `origin` repository for your local files.

NOTE: For more information about http://doc.gitlab.com/ee/workflow/forking_workflow.html[forking^] and http://doc.gitlab.com/ce/gitlab-basics/command-line-commands.html#clone-your-project[cloning^], consult the official http://doc.gitlab.com/ce/[Gitlab documentation^].

[discrete]
=== Using SSH

.Procedure
. Open *Terminal*.
. Navigate to the directory where you want to create the new repository folder.
. Type the following command:
+
[source,options="nowrap",subs="+quotes"]
----
$ git clone git@github.com:__USERNAME__/amq7-documentation-contrib.git
----
. Navigate to the newly created `amq7-documentation-contrib` folder.
+
[source]
----
$ cd amq7-documentation-contrib/
----

[discrete]
=== Using HTTPS

While there are fewer steps in this option, you have to enter your GitHub credentials with every change you make.

.Procedure
. Open *Terminal*.
. Navigate to the directory where you want to create the new repository folder.
. Type the following command:
+
[source,options="nowrap",subs="+quotes"]
----
$ git clone https://github.com/__USERNAME__/amq7-documentation-contrib.git
----
. Enter your GitHub credentials to complete the clone.
. Navigate to the newly created `amq7-documentation-contrib` folder.
+
[source]
----
$ cd amq7-documentation-contrib/
----

[[add-upstream]]
== Add the Upstream as a Remote Repository

Once you have your fork checked out and cloned locally, add the downstream repository as a remote.

[discrete]
=== Using SSH

.Procedure
. List the current remote repositories:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@github.com:__USERNAME__/amq7-documentation-contrib.git (fetch)
origin	git@github.com:__USERNAME__/amq7-documentation-contrib.git (push)
----
. Add the upstream as a remote repository and fetch its contents. This allows you to check out and work with the latest source code.
+
[source]
----
$ git remote add -f upstream  git@github.com:rh-messaging/amq7-documentation-contrib.git
----
. Enter your GitHub credentials to complete the remote add process.
. Verify the new remote was added:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	git@github.com:__USERNAME__/amq7-documentation-contrib.git (fetch)
origin	git@github.com:__USERNAME__/amq7-documentation-contrib.git (push)
upstream	git@github.com:rh-messaging/amq7-documentation-contrib.git (fetch)
upstream	git@github.com:rh-messaging/amq7-documentation-contrib.git (push)
----

[discrete]
=== Using HTTPS

.Procedure
. List the current remote repositories:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	https://github.com/__USERNAME__/amq7-documentation-contrib.git (fetch)
origin	https://github.com/__USERNAME__/amq7-documentation-contrib.git (push)
----
. Add the upstream as a remote repository and fetch its contents. This allows you to check out and work with the latest source code.
+
[source]
----
$ git remote add -f upstream  https://github.com/rh-messaging/amq7-documentation-contrib.git
----
. Enter your GitHub credentials to complete the remote add process.
. Verify the new remote was added:
+
[source,options="nowrap",subs="+quotes"]
----
$ git remote -v
origin	https://github.com/__USERNAME__/amq7-documentation-contrib.git (fetch)
origin	https://github.com/__USERNAME__/amq7-documentation-contrib.git (push)
upstream	https://github.com/rh-messaging/amq7-documentation-contrib.git (fetch)
upstream	https://github.com/rh-messaging/amq7-documentation-contrib.git (push)
----

[[url-update]]
== Updating Repository URLs

If the upstream repository is moved, you can change the downstream URL by using the following command:

[source]
----
$ git remote set-url upstream https://github.com/rh-messaging/amq7-documentation-contrib.git
----

Use the following command any time you need to fetch the latest source code locally:

[source]
----
$ git fetch upstream
----

[[git-setup-references]]
== References

* https://git-scm.com[Official Git Site^]
* https://gitlab.cee.redhat.com/red-hat-jboss-enterprise-application-platform-documentation/eap-documentation/blob/master/internal-resources/contributor-guide.adoc[EAP Contributor Guidelines^]
