// This doc can be the basis for an AMQ Admin Guide. For now it just covers merging PRs in amq7-documentation-contrib and pushing them to GitLab for doc builds.
[[doc-admin-guide]]
= Administrating AMQ 7 documentation

This guide describes how to administer the AMQ 7 documentation GitHub and GitLab repositories. All commits, with the exception of internal resources, are to be merged weekly on Friday by the "Mergemaster".

include::amq7-repositories.adoc[leveloffset=+1]

== Branching overview

The `amq7-documentation-contrib` repo contains several branches, most of which are inactive or deprecated.
The only ones that you need to use are:

`contrib`:: The default branch. All doc contributions are merged into this branch, regardless of release.

`master`:: The master branch for preparing doc builds.

`release-amq-7.<version-number>.x`:: The branch for an AMQ 7.x.y doc release.

== Processing pull requests

After a pull request has passed SME and peer review, it is ready to be merged into the `contrib` branch in the GitHub repo.
This can be done piecemeal, but the current practice is for the "Mergemaster" to merge all pull requests on a weekly basis (Friday, 1pm EDT/EST).

=== Opening the pull request

.Procedure
. In the `amq7-documentation-contrib` repo, click *Pull Requests*.
. Verify that the pull request that you want to merge has the *Ready to Merge* label applied.
+
This label specifies that the changes in the pull request have passed SME and peer reviews.
. Click the pull request to open it.

=== Reviewing the pull request

.Procedure
. Under the pull request title, verify that the pull request is being merged into `rh-messaging:contrib`.
. Review the conversation to ensure all comments have been resolved and that there are not any outstanding, glaring issues that need to be addressed.
. Determine if the pull request can be merged automatically, or if conflicts need to be resolved.
+
If the pull request can be merged automatically, you will see `This branch has no conflicts with the base branch`.

=== Merge the pull request

In most cases, you should be able to merge the pull request automatically.
However, if there are any conflicts, you must resolve them.

[[automatic-merging]]
[discrete]
==== Merging the pull request automatically

.Procedure
. Click the *Squash and merge* button.
+
--
You might need to click the arrow next to *Create a merge commit* to select this option.

Use the squash and merge option rather than the option to create a merge commit. Squashing the commits makes for a cleaner commit history.
--

. Click *Confirm squash and merge*.
+
The pull request is merged into `contrib` and closed.

[discrete]
==== Handling a pull request with conflicts

.Procedure
. Click *Resolve conflicts* to determine the extent of the conflicts.
+
--
* If the conflict is minor, and you can easily see how to resolve it, make the change in the web editor, and then click *Mark as resolved*.
Your changes are committed and added to the pull request.

* If the conflict is extensive or the resolution is unclear, notify the author and ask him or her to make the necessary corrections.
+
For additional information about handling complex merge conflicts, see link:https://gitlab.cee.redhat.com/red-hat-jboss-enterprise-application-platform-documentation/eap-documentation/blob/master/internal-resources/contributor-guide.adoc#fix_rebase_merge_conflicts[Fix Rebase Merge Conflicts^].
--

. When the conflicts are resolved, xref:automatic-merging[merge the pull request].

== Pushing to GitLab for doc builds

The `amq7-docs` repo is the source for the AMQ 7 Preview, Stage, and Production environments.
Therefore, to build the doc, you need to push the content from GitHub to GitLab.

[[merge-to-github]]
=== Merge to the GitHub `master` branch

In `amq7-documentation-contrib`, you need to merge to `master` everything that you want to be included in the doc build.
////
For now this is basically just pushing everything from contrib to master.
If we move to a different branching model with release branches, then we'll need some more info here about cherry picking commits and merging to the proper branches.
////

.Procedure
. In `amq7-documentation-contrib`, navigate to the *Pull requests* tab and then click *New pull request*.
. Click the *base: contrib* button and select `master`.
+
The first button should be `base: master`, and the second button should be `compare: contrib`.
. Click *Create pull request*.
. In the `Title` field, enter a descriptive name (for example, "Doc Build").
. Click *Create pull request*.
. In the pull request, click *Squash and merge*.
+
All of the commits from `contrib` are merged to `master`, and the pull request is closed.

=== Push to GitLab

After merging to `master` everything that you want to be in the doc build, you pull the changes down to a local branch, and then push the commits to the `amq7-docs` GitLab repo.
After pushing to `amq7-docs`, Pantheon automatically builds the docs in the Preview and Stage environments.

.Procedure
. In git, if you do not have a remote repository for `amq7-docs`, then add one:
+
--
[options="nowrap",subs="+quotes"]
----
$ git remote add -f _REPO_NAME_ git@gitlab.cee.redhat.com:AMQ7-documentation/amq7-documentation.git
----

For `__REPO_NAME__`, you can use whatever name you want. For simplicity, you should probably name it `amq7-docs` to match the name of the actual repo.
--

. Fetch the latest from the upstream repository:
+
[options="nowrap",subs="+quotes"]
----
$ git fetch upstream
----

. Do one of the following:
+
--
.Check out a new local branch based on the GitHub `master` branch:
[options="nowrap",subs="+quotes"]
----
$ git checkout -b _BRANCH_NAME_ upstream/master
----

.Reset an existing local branch with the GitHub `master` branch:
[options="nowrap",subs="+quotes"]
----
$ git checkout _BRANCH_NAME_
$ git reset --hard _BRANCH_NAME_ upstream/master
----
--

. Verify that the branch contains everything that you expect:
+
[options="nowrap",subs="+quotes"]
----
$ git log
----

. Push the changes to the `master` branch on the `amq7-docs` repo:
+
[options="nowrap",subs="+quotes"]
----
$ git push -f _GITLAB_REMOTE_REPO_ HEAD:master
----

. If necessary, in `amq7-docs`, verify that everything was pushed to the `master` branch the way you expected.

. Verify that each doc builds successfully on Preview and Stage in Pantheon: link:https://pantheon.cee.redhat.com/#/titles/red_hat_amq[https://pantheon.cee.redhat.com/#/titles/red_hat_amq^]

== Preparing AMQ documentation for release

When an AMQ product release is ready, there are several tasks you must complete to prepare the documentation for the release and push it to Pantheon for publication on the customer portal.

=== Creating a release branch

When it is time to publish the AMQ docs for a release, you should create a release branch.

.Procedure

. Create a release branch from master:
+
--
Release branch names should follow this syntax: `release-amq-7._VERSION_NUMBER_.x`.

[options="nowrap",subs="+quotes"]
----
git fetch upstream
git checkout -b release-amq-7.1.x upstream/master
git push upstream HEAD:release-amq-7.1.x
----
--

. Push the release branch to GitLab:
+
--
[options="nowrap",subs="+quotes"]
----
git push amq-docs HEAD:release-amq-7.1.x
----
--

. In Pantheon, navigate to the release.

. For each title, click the drop-down for the `Preview` branch, select *Edit Configuration*, and then select the release branch that you created.

. Repeat the previous step for the `Stage` branch.

=== Tagging a release

A tag represents a snapshot of the repository at a particular point in time. After creating a release branch, you should create a tag to identify exactly what was delivered for the release. If you ever need to republish the documentation on the release branch (such as for a hotfix or asynchronous doc update after the initial release), the tag will identify what was originally published.

.Procedure

. Check out the release branch.
+
[options="nowrap",subs="+quotes"]
----
git checkout release-amq-7.1.x
----

. Create the tag.
+
[options="nowrap",subs="+quotes"]
----
git tag 7.1.0 -m "Release 7.1"
----

. Push the tag to the GitHub repo.
+
[options="nowrap",subs="+quotes"]
----
git push upstream HEAD --tags 7.1.0
----

. In the GitHub repo, view the tag to verify that it looks correct.

=== Cherry-picking a commit to a release branch

Even though release branches are created at the end of the release process (typically immediately prior to publishing the docs on the portal), it may be necessary to update a doc in this release after the release has been published. You can do this by cherry-picking the commit to the release branch.

.Procedure

. Merge the PR into the default branch just as you would normally do.

. Fetch the latest changes from GitHub:
+
[options="nowrap",subs="+quotes"]
----
git fetch upstream
----

. Create a new topic branch from the release branch.
+
--
In this example, a new branch for AMQDOC-2752 is being created for the 7.1.x release branch.

[options="nowrap",subs="+quotes"]
----
git checkout -b amqdoc-2752 upstream/release-amq-7.1.x
----
--

. Using GitHub or the `git log` command, find the number of the commit that was merged to contrib.

. Cherry pick the commit into your topic branch.
+
[options="nowrap",subs="+quotes"]
----
git cherry-pick cafd2a9
----

. Push the changes to your own forked repo:
+
[options="nowrap",subs="+quotes"]
----
git push origin HEAD
----

. In GitHub, create a PR from your topic branch with the cherry-picked commit to the release branch.

. Merge the PR. Be sure to change the “base fork” to the release branch.

. If necessary, push to Pantheon to build the docs that are affected by the cherry-picked commit.
