[id='ref_intro']

= Introduction

As a {GROUP} developer or technical writer, you can contribute to {GROUP} technical documentation to ensure that product content is as up to date as possible. This document describes the required components and procedures for contributing to {GROUP} documentation and applies to both {GROUP_KIE} community and {GROUP_BA} enterprise content. Differences between community and enterprise content or processes are described explicitly. If you have any questions, <<_contact_information, contact us>>.

The following abbreviations are used throughout this guide:

* *{GROUP_KIE}:* Knowledge Is Everything open-source community group for business management software products, including Drools, jBPM, and OptaPlanner
* *{GROUP_BA}:* {GROUP_BA} group with software products that correspond with KIE community products, including {DM} (Drools-based), {PAM} (jBPM-based), and {PLANNER} (OptaPlanner-based)
* *kie-docs:* The {GROUP_BOTH} documentation repository in https://github.com/kiegroup/kie-docs[GitHub]
* *BXMS:* Deprecated abbreviation for {GROUP_BA} software products, still used in some internal Red Hat projects and tools (example: <<jira-introduction,BXMSDOC JIRA Project>>)

To get started, read the <<_contributing>> section.
