
= System Requirements

To work with the {PRODUCT} repository, you need the following software:

== Required

Git::
+
--
Git is a version-control system. To install Git on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install git
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[official Git documentation].
--

Asciidoctor (enterprise documentation)::
+
--
A quick and light tool for local builds that allows you to check factual correctness or flow of information. It does not require any additional packages to be installed, but its output differs visually (and to a very little extent in contentfootnote:[For example, Asciidoctor does not produce section numbers when generating links]) from the final version that is built using Pantheon or ccutil.

To install Asciidoctor on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install asciidoctor
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://asciidoctor.org/#installation[official Asciidoctor documentation].
--

Maven (community documentation)::
+
--
A software project management and comprehension tool that can be used to build the community documentation set. To install Maven on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install maven
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://maven.apache.org/[official Maven documentation].
--
Atom (text editor)::
+
--
A text editor that is modern, approachable, yet hackable to the core, and that you can customize to do anything but also use productively without touching a config file. You can use another text editor of your choice, such as https://wiki.gnome.org/Apps/Gedit[gedit], but Atom is recommended for its extensive support of Asciidoctor and many helpful add-on packages.

To install Atom on Fedora, CentOS, or RHEL, go to the Atom https://atom.io/[homepage] from your web browser and click to download the RPM version. Then run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install -y atom.x86_64.rpm
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://flight-manual.atom.io/[official Atom documentation].
--

== Optional

ifdef::INTERNAL[]
ccutil::
A tool whose output greatly resembles the final document that is generated by Pantheon and pushed to production. Given this, it is the superior option when verifying content quality. However, it is much slower because it converts the input to DocBook first, and requires Red Hat brand packages and other tools that must be downloaded first.
+
To install ccutil, follow the instructions in the https://pantheon.cee.redhat.com/help/user-guide/#ccutil-install[Pantheon User Guide].
+
If you encounter a Ruby-related error while running ccutil, try installing the following packages:

  # yum install ruby-devel rubygem-nokogiri

endif::INTERNAL[]

Meld::
A graphical tool for comparing files. This tool is useful for comparing Git revisions and resolving merge conflicts.
+
To install Meld on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

  # yum install meld
