[id='ref_required-doc-tools']

= Required documentation tools

To work with the {GROUP} repository, you need the following software:

Git::
+
--
Git is a version-control system. To install Git on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install git
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[official Git documentation].
--

Atom (text editor)::
+
--
A text editor that is modern, approachable, yet hackable to the core, and that you can customize to do anything but also use productively without touching a config file. You can use another text editor of your choice, such as https://wiki.gnome.org/Apps/Gedit[gedit], but Atom is recommended for its extensive support of Asciidoctor and many helpful add-on packages.

To install Atom on Fedora, CentOS, or RHEL, go to the Atom https://atom.io/[homepage] from your web browser and click to download the RPM version. Then run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install -y atom.x86_64.rpm
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://flight-manual.atom.io/[official Atom documentation].
--

Asciidoctor::
+
--
A quick and light tool for local builds that allows you to check factual correctness or flow of information. It does not require any additional packages to be installed, but its output differs visually (and to a very little extent in contentfootnote:[For example, Asciidoctor does not produce section numbers when generating links]) from the final version that is built using Pantheon or ccutil.

To install Asciidoctor on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install asciidoctor
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://asciidoctor.org/#installation[official Asciidoctor documentation].
--

Maven 3.5.4 or later (community documentation)::
+
--
A software project management and comprehension tool that can be used to build the community documentation set. To install Maven on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):

[source,bash]
----
# yum install maven
----

On Windows, Mac OS X, and other Linux distributions, follow the instructions in the http://maven.apache.org/[official Maven documentation].
--

ifdef::INTERNAL[]
ccutil::
A tool whose output greatly resembles the final document that is generated by Pantheon and pushed to production. Given this, it is the superior option when verifying content quality. However, it is much slower because it converts the input to DocBook first, and requires Red Hat brand packages and other tools that must be downloaded first.
+
--
To install ccutil, follow the instructions in the https://pantheon.cee.redhat.com/help/user-guide/#ccutil-install[Pantheon User Guide].

If you encounter a Ruby-related error while running ccutil, try installing the following packages:

[source,bash]
----
# yum install ruby-devel rubygem-nokogiri
----
--

proposal-d::
A repository in https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/proposal-d/tree/master[GitLab] that contains scripts for preparing and building the upstream `kie-docs` repository for internal Pantheon builds.
+
--
The following are the essential scripts available in `proposal-d`:

* *ba-build:* Use this script to compile {GROUP} documents using either Asciidoctor (`ba-build -a`) or `ccutil` (`ba-build`) from the `kie-docs` repository. This script builds enterprise content in a way that supports single sourcing between community and enterprise documentation.
* *ba-translate:* Use this script to prepare a branch of the upstream `kie-docs` repository for publishing in Pantheon (`ba-translate $BRANCH_NAME`). This script restructures enterprise content in a way that supports the required structure for publishing in Pantheon, and stores the results in a `kie-docs-translator` repository https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/kie-docs-translator/tree/master[GitLab]. The results are force-pushed, so there is no risk of conflicts.
* *bxms-build / bxms-translate-branch:* Use these scripts instead of `ba-build` and `ba-translate` (respectively) for all {GROUP_BA} 7.0 content.

NOTE: To build and publish Red Hat JBoss BPMS/BRMS 6.x content, use `ccutil` or Asciidoctor directly, without `proposal-d` tools.

NOTE: Do not use the old `bxms-translate` script, which translated every branch. This script uses the old (PAM/DM 7.0) translate mechanism and running it breaks new-structure (PAM/DM 7.1+) branches.

For complete installation instructions and information about `proposal-d` scripts, see the `proposal-d` repository and `README` file in https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/proposal-d/tree/master[GitLab].
--
endif::INTERNAL[]

Meld (optional)::
A graphical tool for comparing files. This tool is useful for comparing Git revisions and resolving merge conflicts.
+
--
To install Meld on Fedora, CentOS, or RHEL, run the following command (in Fedora, replace `yum` with `dnf`):
[source,bash]
----
# yum install meld
----
--
