[id='ref_kie-docs-repo-structure']

= Filesystem layout of kie-docs repository

The following is the general structure of the `kie-docs` repository:

----
├── _artifacts
├── _images
├── assemblies
    ├── assembly_dmn-models
        ├── dm
            ├── master-docinfo.xml
            └── master.adoc
        ├── drools
        ├── jbpm
        ├── pam
        └── main.adoc
    ├── ...
├── doc-content
    ├── drools-docs
        └── src
            └── main
                └── asciidoc
                    ├── DMN
                        ├──dmn-elements-con.adoc
                        ├── ...
                    ├── ...
    ├── enterprise-only
        ├── installation
            ├──controller-con.adoc
            ├── ...
        ├── ...
    ├── ...
├── ...
└── README.adoc
----

The following are descriptions of some of the core folders in this repository structure:

* *_artifacts:* Directory with document attributes that render according to target output (community, enterprise, or a specific product).
* *_images:* Directory with all images used in documentation, divided by relevant sub-directory.
* *assemblies:* List of assembly folders used to build content for the Red Hat Customer Portal. Each assembly folder includes a `main.adoc` assembly file that defines the assembly (document) content, and product-specific build folders (`dm`, `drools`, `jbpm`, `pam`) that compile the assembly into the rendered output for {DM}, Drools, jBPM, or {PAM}. Each product-specific build folder contains a `master-docinfo.xml` and `master.adoc` files with metadata required for publishing to the Red Hat Customer Portal.
+
NOTE: Only the enterprise `dm` and `pam` folders are currently used in production. The community `drools` and `jbpm` folders are preview build folders that are currently not used to build community documents. To build community documents, run `mvn clean install -Dfull` at the `kie-docs`, `kie-docs/doc-content`, or `kie-docs/doc-content/$DOC_FOLDER`. For more information about building community or enterprise documents, see <<building_locally>>.

* *doc-content:* Directory with all `.adoc` content files. Community `drools-docs`, `jbpm-docs`, and `optaplanner-wb-es-docs` folders are in a Maven structure to enable a `mvn clean install -Dfull` build. All content files in community folders are or can be used in enterprise assembly builds from the `assemblies` folder for the Red Hat Customer Portal. Content files in the `enterprise-only` folder either apply only to {GROUP_BA} products or are files that have not yet been reconciled with community content.
