
= Metadata

In addition to book source files and images, the repository also contains metadata files that are necessary for building the documentation for production, including:

[id='master-docinfo.xml']
docs/$BOOK/src/main/asciidoc/$PRODUCT/master-docinfo.xml:: An XML file in each product subdirectory in a book's main directory, which is used when building books internally for production. This file is not used when building the book with Asciidoctor.
+
All AsciiDoc attributes and other language constructs are replaced before the book is built, so they can be used to customize this file (typically `\{PRODUCT_VERSION\}` inside the `<productnumber/>` XML tag).
+
For more information about the `master-docinfo.xml` file, see the https://pantheon.cee.redhat.com/help/user-guide/#docinfo_xml[Pantheon documentation].

[id='document-attributes']
docs/shared-kie-docs/src/main/asciidoc/Product/document-attributes.adoc:: An AsciiDoc file that contains the definitions of the attributes (entities in DocBook) used throughout the documentation.
+
The attributes defined in this file are used in all the product configurations of all books--community, {BRMS}, and {BPMS}. The repository also contains files with attributes for a particular enterprise product (`docs/shared/document-attributes-bpms.adoc` and `docs/shared/document-attributes-brms.adoc`, specifically). These files are conditionally included at the end of this main definitions file, and the values in them overwrite the values defined previously.
