// When including this file, you must specify one of the attributes: TOOL_CCUTIL or TOOL_ASCIIDOCTOR

ifdef::TOOL_ASCIIDOCTOR[]
:TOOL: Asciidoctor
endif::TOOL_ASCIIDOCTOR[]

ifdef::TOOL_CCUTIL[]
:TOOL: ccutil
endif::TOOL_CCUTIL[]

= Building Locally with {TOOL}

Build books locally using {TOOL} to check how the book renders with your changes, before pushing to the repository. For more information about {TOOL}, see <<_system_requirements>>.

[float]
== Prerequisites

* {TOOL}. For more information, see <<_system_requirements>>.

[float]
== Procedure

To build a book on your local machine, follow these steps:

.Building and Previewing a Book Using {TOOL}
. Navigate to <<product_directories,a product subdirectory>> inside the book's directory (For example: `_$REPOSITORY_PATH_/docs/product-installation-guide/src/main/asciidoc/bpms` for the Red Hat JBoss BPM Suite Installation Guide).

ifdef::TOOL_ASCIIDOCTOR[]
. Add the `topics` symlink in the `bpms` or `brms` directory:
+
[source,bash]
----
$ ln -s .. topics
----

. Add the `product-shared-docs` symlink into the directory with `.adoc` files, that is `asciidoc`
+
[source,bash]
----
## Change one level higher to be in the asciidoc directory ##
$ cd ..
## Create the product-shared-docs symlink ##
$ ln -s ../../../../shared-kie-docs/src/main/asciidoc/Product product-shared-docs
----

. Build the book:
+
[source,bash]
----
$ cd bpms #or brms, depending on what product you want to build the book for
$ asciidoctor master.adoc
----
. Preview the document in a web browser:
+
[source,bash]
----
$ firefox master.html
----
+
NOTE: Replace `firefox` with a browser of your choice.

WARNING: Do not push the symlinks into your topic branch. The symlinks may cause the Jenkinscat build to fail.
endif::TOOL_ASCIIDOCTOR[]

ifdef::TOOL_CCUTIL[]
. Follow the instructions in the https://gitlab.cee.redhat.com/red-hat-jboss-bxms-documentation/proposal-d/tree/master[proposal-d] repository for setting up the `bxms-build` script.
. Change into the `bpms` or `brms` directory.
. Build and preview the source by running:
+
--
  $ bxms-build compile --lang en-US --open

This command automatically launches your default browser with the output. To build without previewing, remove the `--open` flag from the command. For more information, see https://pantheon.cee.redhat.com/help/user-guide/#ccutil-commands[ccutil commands] in the Pantheon User Guide.
--
. Alternatively, preview the source in web browser:
+
[source,bash]
----
$ firefox build/tmp/en-US/html-single/index.html
----
+
NOTE: Replace `firefox` with a browser of your choice.
endif::TOOL_CCUTIL[]

ifdef::TOOL_CCUTIL[]
[float]
== Related Information

* https://pantheon.cee.redhat.com/help/user-guide/#ccutil-commands[List of ccutil commands] on the Pantheon help site.
endif::TOOL_CCUTIL[]

:TOOL!:
